
name: action-demo
on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
    - name: run java
      run: java -version
    - name: ls
      run: ls
